creation_rules:
  - path_regex: .infra/helm/dev/*
    gcp_kms: projects/kitabisa-stg/locations/global/keyRings/sops/cryptoKeys/sops-key

  - path_regex: .infra/helm/stg/*
    gcp_kms: projects/kitabisa-stg/locations/global/keyRings/sops/cryptoKeys/sops-key

  - path_regex: .infra/helm/uat/*
    gcp_kms: projects/kitabisa-uat/locations/global/keyRings/sops/cryptoKeys/sops-key

  - path_regex: .infra/helm/prod/*
    gcp_kms: projects/kitabisa/locations/global/keyRings/sops/cryptoKeys/sops-key
