secrets:
  envFrom:
    - "{{ .Values.meta.name }}-config-{{ .Values.meta.env }}"

configMaps:
  envFrom:
    - "{{ .Values.meta.name }}-config-{{ .Values.meta.env }}"

migration:
  enabled: true

  command:
    - golang-poc
    - migrate

  resources:
    requests:
      cpu: 100m
      memory: 512Mi
    limits:
      cpu: 200m
      memory: 1Gi
