secret:
    enabled: ENC[AES256_GCM,data:9HYLlQ==,iv:ipBAXMTAX36y5Km6OjxYlKJgzLfLbWN/JwRE/IMCiZE=,tag:d0MwZYvC7K3yRskzRwZ5aA==,type:bool]
    data:
        APP_SECRET: ENC[AES256_GCM,data:3lKwIVvqy1UF6g==,iv:cuSkHibHWU7BzdGthCgIRfxlizb0QtkxUenhto2RBdM=,tag:9LJP9danhVrHaB/XklS2hQ==,type:str]
        EXAMPLE_USER: ENC[AES256_GCM,data:B/NwNk4=,iv:c25BlTtYtQzMtjCaix40/tOxPWxS8i0XI7VseTgdcNg=,tag:Yc5tppnNzI2iq4FqogGp5A==,type:str]
        EXAMPLE_PASSWORD: ENC[AES256_GCM,data:rNYwML0=,iv:iEKIDKYApnqBY3+47RHoGqW2/nADNgaPwFkrttHImBg=,tag:IGsS5OmxHUMcCWcExC5xWA==,type:str]
        EXAMPLE_BLANK_PASSWORD: ""
sops:
    kms: []
    gcp_kms:
    -   resource_id: projects/kitabisa-stg/locations/global/keyRings/sops/cryptoKeys/sops-key
        created_at: '2020-12-11T02:57:40Z'
        enc: CiQAS2FqNW+FSn0DKSRQ3u28BsmueQl3XVUYI1to7Q/9aLH7sCkSSQB/YcCYF2dXMb+RYkUmXXriBaLZAK45ix3dF9rG8od8PAkHAb1w50fYqjMPB9irv54WxYfMSADzZsazWkWUPIfOPMR7Jdh3pYM=
    azure_kv: []
    hc_vault: []
    lastmodified: '2020-12-11T02:57:41Z'
    mac: ENC[AES256_GCM,data:h31gJgCqf6XCJaisbBnvAEkWI7VxScqmpZBo7zLAR1P7qoKkEuqYhOlPjRYiFnmTigk05K1GxLq6NgDQ0r2CNAdC/0Qny+cJYnq11EKdYfGglhmwxHiWONNlnZ5jbDfX0YfTjQEsbj4Qhr3FDem1hO/MWQ0WPWr6MJoxQrfC/8Q=,iv:N3fXqZN4advqcWW4QKjz0UnZ9cysKhjl9GZrN2Y16AI=,tag:m+3iO3TSvHQvDFP4HhNXkw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.6.1
