
repositories:
  - name: kitabisa
    url: https://{{ requiredEnv "CHARTMUSEUM_HOST" }}
    username: {{ requiredEnv "CHARTMUSEUM_USER" }}
    password: {{ requiredEnv "CHARTMUSEUM_PASS" }}

  - name: bitnami
    url: https://charts.bitnami.com/bitnami


releases:
  
  
  - name: {{ requiredEnv "APP_NAME" }}-redis
    namespace: {{ requiredEnv "APP_NAME" }}
    labels:
      tier: data
      type: dependency
    chart: bitnami/redis
    version: 15.6.2
    values:
      - {{ requiredEnv "ENV" }}/redis.yaml

  - name: {{ requiredEnv "APP_NAME" }}-config-{{ requiredEnv "ENV" }}
    namespace: {{ requiredEnv "APP_NAME" }}
    labels:
      tier: config
      type: main
    chart: kitabisa/config
    version: ~0.4.0
    values:
      - {{ requiredEnv "ENV" }}/config.yaml
      - config-response-code.yaml
      - values.yaml.gotmpl
    secrets:
      - {{ requiredEnv "ENV" }}/secret.yaml
  

  
  
  - name: {{ requiredEnv "APP_NAME" }}-migration-{{ requiredEnv "ENV" }}
    namespace: {{ requiredEnv "APP_NAME" }}
    labels:
      tier: migration
      type: main
    chart: kitabisa/migration
    version: ~0.4.0-alpha
    values:
      - {{ requiredEnv "ENV" }}/migration.yaml
      - volume.yaml
      - values.yaml.gotmpl
  
    needs:
      
      
      - {{ requiredEnv "APP_NAME" }}/{{ requiredEnv "APP_NAME" }}-redis
      - {{ requiredEnv "APP_NAME" }}/{{ requiredEnv "APP_NAME" }}-config-{{ requiredEnv "ENV" }}
      

  
  
  
  - name: {{ requiredEnv "APP_NAME" }}-server-{{ requiredEnv "ENV" }}
    namespace: {{ requiredEnv "APP_NAME" }}
    labels:
      tier: app
      type: main
    chart: kitabisa/app
    version: ~0.17.0-alpha
    values:
      - {{ requiredEnv "ENV" }}/server.yaml
      - volume.yaml
      - values.yaml.gotmpl
    hooks:
      - events: ["presync"]
        showlogs: true
        command: kubectl
        args: ["label", "--overwrite", "namespaces", "{{ requiredEnv "APP_NAME" }}", "istio-injection=enabled"]
    needs:
    
      
      
      - {{ requiredEnv "APP_NAME" }}/{{ requiredEnv "APP_NAME" }}-redis
      - {{ requiredEnv "APP_NAME" }}/{{ requiredEnv "APP_NAME" }}-config-{{ requiredEnv "ENV" }}
      
      
      - {{ requiredEnv "APP_NAME" }}/{{ requiredEnv "APP_NAME" }}-migration-{{ requiredEnv "ENV" }}
      

  
  
  
  - name: {{ requiredEnv "APP_NAME" }}-worker-{{ requiredEnv "ENV" }}
    namespace: {{ requiredEnv "APP_NAME" }}
    labels:
      tier: app
      type: main
    chart: kitabisa/app
    version: ~0.17.0-alpha
    values:
      - {{ requiredEnv "ENV" }}/worker.yaml
      - volume.yaml
      - values.yaml.gotmpl
    
    needs:
      
      
      - {{ requiredEnv "APP_NAME" }}/{{ requiredEnv "APP_NAME" }}-redis
      - {{ requiredEnv "APP_NAME" }}/{{ requiredEnv "APP_NAME" }}-config-{{ requiredEnv "ENV" }}
      
      
      - {{ requiredEnv "APP_NAME" }}/{{ requiredEnv "APP_NAME" }}-migration-{{ requiredEnv "ENV" }}
      

  
  
  - name: {{ requiredEnv "APP_NAME" }}-user-{{ requiredEnv "ENV" }}
    namespace: {{ requiredEnv "APP_NAME" }}
    labels:
      tier: user
      type: main
    chart: kitabisa/user
    version: ~0.3.0
    values:
      - {{ requiredEnv "ENV" }}/user.yaml
      - values.yaml.gotmpl

  - name: {{ requiredEnv "APP_NAME" }}-debugger
    namespace: {{ requiredEnv "APP_NAME" }}
    labels:
      tier: debugger
      type: optional
    chart: kitabisa/debugger
    installed: {{ requiredEnv "ENV" | ne "prod" }}
  
