name: Generating Docs

on:
  push:
    branches:
      - master
    paths:
      - 'docs/*.mmd'
      - 'docs/*.py'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checking out repository
        uses: actions/checkout@v2

      - name: Generate architecture diagram
        run: make architecture

      - name: Generate other diagram with mermaid js
        run: make mermaid-diagram

      - name: Get generated files
        id: getgenerated
        run: |
          echo "::set-output name=files::$(find docs/out -type f -name '*' |xargs echo)"

      - name: diagram generated
        run: |
          echo ${{ steps.getgenerated.outputs.files }}

      - name: Copy files to system-diagram repository
        uses: nkoppel/push-files-to-another-repository@v1.1.0
        env:
          API_TOKEN_GITHUB: ${{ secrets.GH_TOKEN }}
        with:
          source-files: ${{ steps.getgenerated.outputs.files }}
          destination-username: 'kitabisa'
          destination-repository: 'system-diagram'
          destination-directory: 'diagrams/backend/${{ github.event.repository.name }}'
          commit-email: 'engineer@kitabisa.com'
          commit-username: 'engineer'